name: Image pusher and project build

on: [push]

jobs:
  get_images:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python getimages.py

      - uses: stefanzweifel/git-auto-commit-action@v4
    #build and deploy
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
          node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Build
      - run: npm install && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages #The branch the action should deploy to.
          folder: build #The folder the action should deploy.
        

        
